name: ada
version: "3.8"
services:
  # ---------------  PostgreSQL ---------------
  db:
    build:
      context: postgresql
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ada
      POSTGRES_PASSWORD: ada
      POSTGRES_DB: adadb
    volumes:
      - postgre_volume:/var/lib/postgresql/data"

  # ---------------  PGADMIN ---------------
  pgAdmin:
    image: dpage/pgadmin4:6.9
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: alzheimer.d.app@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: adaadadb
    restart: always

  # ---------------  Python Service ---------------
  python:
    build:
      context: ../alzheimer-diagnosis-pred-service
      dockerfile: Dockerfile
    #command: uvicorn main:app
    restart: always
    ports:
      - "80:80"

volumes:
  postgre_volume: