server:
  port: 8080

spring:
  jackson:
     serialization:
       fail-on-empty-beans: false
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/adadb
    username: ada
    password: ada
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_schema: rest
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 600
  refreshTokenExpiration: 86400
  route:
    authentication:
      path: auth
      logout: logout
      refresh: refresh
      forgetPassword: forgetPassword
      changePassword: changePassword
